# Site settings
baseurl = "http://nodejh.com/"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "zh-cn"
title = "blackcater's blog, dedicated to becoming fullstack developer and be curious about all the new technology!"
theme = "cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "your_google_analytics_code"
hasCJKLanguage = true

[params]
	name = "blackcater's blog"
	description = "blackcater's blog, dedicated to becoming fullstack developer and be curious about all the new technology!"
	bio = "一心所向，必有回响"
	# Enter optionally your twitter account
	twitter = "your_twotter"
	enableRSS = true

	# Disqus comment
	disqusShortname = "your_disqus_short_name"
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = false

	# Duoshuo comment
	duoshuoShortname = "your_duoshuo_short_name"
	# Disable duoshuo comments by set `enableDuoshuo = "false"`
	enableDuoshuo = false

	# Github Issue comment
	gitmentOwner = 'blackcater'
	gitmentRepo = 'blackcater.github.io'
	gitmentClientId = 'dc3a9667717ca3e9e938'
    gitmentClientSecret = '291a0e09dca280e2b4eeaab7fc536d3b7067c5d4'
	# Disable github issue comments by set `enableGitment = "false"`
	enableGitment = true

	enableGithubIssuesTips = false

	# Enable googleAnalytics
	enableGoogleAnalytics = false

	# Enable baiduAnalytics
	enableBaiduAnalytics = false
	# Baidu Tongji Code
	baiduAnalytics = 'your_baidu_tongji_code'

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I am so interesting."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = ""


# Add additional social link entries underneath
[social]
    github = "https://github.com/blackcater"
    weibo = "your_weibo_link"
    twitter = "https://twitter.com/tomtang2015"
