# Header Menu
menu:
  Home:
    url: /
    icon: home
  Archives:
    url: /archives
    icon: archive
  Tags:
    url: /all-tags
    icon: tags
  Github:
    url: https://github.com/blackcater
    icon: github-alt
  Twitter:
    url: https://twitter.com/tomtang2015
    icon: twitter
  Weibo:
    url: http://weibo.com/tangyinong2013
    icon: weibo
rss: /atom.xml

# Set to false to disable banner
use_header_cover: true

# URL of the banner image
# Put your custom banner image under
# the theme's img folder: your-blog/themes/minimal-dual/source/img/
# and modify index_cover's value like so:
# index_cover: /img/your-custom-banner.jpg
# or
# Put your custom banner image under
# your blog's images folder: your-blog/source/images/
# and modify index_cover's value like so:
# index_cover: /images/your-custom-banner.jpg
# or
# Specify an online resource like so:
# index_cover: http://somewhere.com/path/to/banner.jpg
index_cover: /img/banner-3.png

widgets:
- category
- tag
- archive

# widget behavior
archive_type: 'monthly'
show_count: false

# favicon
favicon: /favicon.ico

# Google Analytics Tracking ID
google_analytics:
